/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'shrikantsonone' at '2/19/18 11:33 AM' with Gradle 2.14.1
 *
 * @author shrikantsonone, @date 2/19/18 11:33 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
